'use client';

import { useState, useEffect } from 'react';
import { supabase, isSupabaseEnabled } from '@/lib/supabase';
import { getActiveFarmerId, getActiveFarmerProfile } from '@/lib/farmer-auth';
import type { CropRecommendation, SoilData } from '@/lib/types';
import dynamic from 'next/dynamic';
const SoilHistoryChart = dynamic(() => import('@/components/SoilHistoryChart'), { ssr: false });

type Tab = 'form' | 'crops' | 'correction';

function shareOnWhatsApp(form: SoilData, result: CropRecommendation) {
  const crops = result.topCrops.map((c, i) => `${i + 1}. ${c.name} — Yield: ${c.expectedYield}, Cost: ${c.inputCostEstimate}`).join('\n');
  const text = `🌾 *Arjuna Agri — Soil Report*\n📍 Location: ${form.location}\n\n*Soil Data:*\nN: ${form.nitrogen} | P: ${form.phosphorus} | K: ${form.potassium} kg/ha\npH: ${form.ph} | Moisture: ${form.moisture}%\n\n*Top Crops:*\n${crops}\n\n*Summary:* ${result.summary}\n\n_Generated by Arjuna Agri AI_`;
  window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
}

async function downloadPDF(form: SoilData, result: CropRecommendation) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const green = [22, 163, 74] as [number, number, number];
  const dark = [10, 36, 20] as [number, number, number];
  const w = 210;

  // Header
  doc.setFillColor(...green);
  doc.rect(0, 0, w, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20); doc.setFont('helvetica', 'bold');
  doc.text('Arjuna Agri — Soil Analysis Report', 15, 12);
  doc.setFontSize(10); doc.setFont('helvetica', 'normal');
  doc.text(`Location: ${form.location}  |  Date: ${new Date().toLocaleDateString('en-IN')}`, 15, 22);

  // Soil Data
  doc.setTextColor(...dark); doc.setFontSize(13); doc.setFont('helvetica', 'bold');
  doc.text('Soil Data', 15, 42);
  doc.setFontSize(10); doc.setFont('helvetica', 'normal');
  const soilData = [['Nitrogen (N)', `${form.nitrogen} kg/ha`], ['Phosphorus (P)', `${form.phosphorus} kg/ha`], ['Potassium (K)', `${form.potassium} kg/ha`], ['pH Level', `${form.ph}`], ['Moisture', `${form.moisture}%`]];
  soilData.forEach(([k, v], i) => {
    doc.setFillColor(i % 2 === 0 ? 240 : 255, i % 2 === 0 ? 253 : 255, i % 2 === 0 ? 244 : 255);
    doc.rect(15, 46 + i * 8, 180, 8, 'F');
    doc.setTextColor(80, 80, 80); doc.text(k, 18, 51.5 + i * 8);
    doc.setTextColor(22, 101, 52); doc.setFont('helvetica', 'bold');
    doc.text(v, 140, 51.5 + i * 8);
    doc.setFont('helvetica', 'normal');
  });

  // Summary
  let y = 100;
  doc.setTextColor(...green); doc.setFontSize(13); doc.setFont('helvetica', 'bold');
  doc.text('AI Summary', 15, y);
  doc.setFontSize(10); doc.setFont('helvetica', 'normal'); doc.setTextColor(60, 60, 60);
  const sumLines = doc.splitTextToSize(result.summary, 175);
  doc.text(sumLines, 15, y + 8); y += 8 + sumLines.length * 6 + 6;

  // Top Crops
  doc.setTextColor(...dark); doc.setFontSize(13); doc.setFont('helvetica', 'bold');
  doc.text('Recommended Crops', 15, y); y += 8;
  result.topCrops.forEach((crop, i) => {
    doc.setFillColor(240, 253, 244);
    doc.rect(15, y, 180, 28, 'F');
    doc.setTextColor(22, 101, 52); doc.setFont('helvetica', 'bold'); doc.setFontSize(11);
    doc.text(`${i + 1}. ${crop.name}`, 18, y + 7);
    doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(60, 60, 60);
    doc.text(`Yield: ${crop.expectedYield}  |  Cost: ${crop.inputCostEstimate}`, 18, y + 14);
    const careLines = doc.splitTextToSize(crop.careTips, 170);
    doc.text(careLines, 18, y + 20); y += 32;
  });

  // Soil Correction
  if (y < 240) {
    doc.setTextColor(...dark); doc.setFontSize(13); doc.setFont('helvetica', 'bold');
    doc.text('Soil Correction Plan', 15, y); y += 8;
    const plan = result.soilCorrectionPlan;
    [['Nitrogen Fix', plan.nitrogenFix], ['Phosphorus Fix', plan.phosphorusFix], ['Potassium Fix', plan.potassiumFix], ['pH Correction', plan.phCorrection], ['Organic Option', plan.organicAlternatives]].forEach(([k, v]) => {
      doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(22, 163, 74);
      doc.text(k + ':', 18, y);
      doc.setFont('helvetica', 'normal'); doc.setTextColor(60, 60, 60);
      const lines = doc.splitTextToSize(v, 150); doc.text(lines, 55, y); y += lines.length * 5 + 3;
    });
  }

  // Footer
  doc.setFillColor(...green);
  doc.rect(0, 287, 210, 10, 'F');
  doc.setTextColor(255, 255, 255); doc.setFontSize(8);
  doc.text('Generated by Arjuna Agri — AI Precision Farming  |  arjuna-agri.vercel.app', 15, 293);

  doc.save(`soil-report-${form.location.replace(/[^a-z0-9]/gi, '-')}-${Date.now()}.pdf`);
}

export default function SoilPage() {
  const [tab, setTab] = useState<Tab>('form');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState<CropRecommendation | null>(null);
  const [form, setForm] = useState<SoilData>({ nitrogen: 0, phosphorus: 0, potassium: 0, ph: 6.5, moisture: 40, location: '', preferred_crop: '' });
  const [uploadFile, setUploadFile] = useState<File | null>(null);
  const [uploadPreview, setUploadPreview] = useState<string>('');
  const [extracting, setExtracting] = useState(false);
  const [extractMsg, setExtractMsg] = useState('');

  useEffect(() => {
    const fetchFarmer = async () => {
      const farmerId = await getActiveFarmerId();
      if (!farmerId) return;
      if (isSupabaseEnabled && supabase) {
        const { data } = await supabase.from('farmers').select('village, state').eq('id', farmerId).single();
        if (data) setForm((f) => ({ ...f, location: `${data.village}, ${data.state}` }));
      } else {
        const profile = await getActiveFarmerProfile();
        if (profile) setForm((f) => ({ ...f, location: `${profile.village}, ${profile.state}` }));
      }
    };
    fetchFarmer();
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      const res = await fetch('/api/crop-recommend', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });
      if (res.status === 429) throw new Error('⏳ Free API quota exhausted. Try again in 1 minute, or add a second Gemini key in .env.local as GEMINI_API_KEY_2');
      if (!res.ok) throw new Error('AI request failed');
      const data: CropRecommendation = await res.json();
      setResult(data);
      const farmerId = await getActiveFarmerId();
      const report = { id: `local_${Date.now()}`, farmer_id: farmerId || '', ...form, recommendations: data, created_at: new Date().toISOString() };
      if (isSupabaseEnabled && supabase && farmerId) {
        await supabase.from('soil_reports').insert([{ farmer_id: farmerId, nitrogen: form.nitrogen, phosphorus: form.phosphorus, potassium: form.potassium, ph: form.ph, moisture: form.moisture, location: form.location, preferred_crop: form.preferred_crop || null, recommendations: data }]);
      } else {
        localStorage.setItem('latest_soil_report', JSON.stringify(report));
      }
      // Save to soil history for NPK charts
      try {
        const historyRaw = localStorage.getItem('soil_history');
        const history = historyRaw ? JSON.parse(historyRaw) : [];
        history.push({ date: new Date().toLocaleDateString('en-IN', { day:'numeric', month:'short' }), n: form.nitrogen, p: form.phosphorus, k: form.potassium, ph: form.ph });
        if (history.length > 10) history.shift(); // keep last 10
        localStorage.setItem('soil_history', JSON.stringify(history));
      } catch { /* ignore */ }
      setTab('crops');
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Something went wrong');
    } finally { setLoading(false); }
  };

  const handleFileChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploadFile(file);
    setExtractMsg('');

    // Show preview for images
    if (file.type.startsWith('image/')) {
      const reader = new FileReader();
      reader.onload = (ev) => setUploadPreview(ev.target?.result as string);
      reader.readAsDataURL(file);
    } else {
      setUploadPreview('');
    }

    // Auto-extract on file pick
    await extractFromFile(file);
  };

  const extractFromFile = async (file: File) => {
    setExtracting(true);
    setExtractMsg('');
    try {
      let base64: string;
      let mimeType: string;

      if (file.type === 'application/pdf') {
        // Convert PDF first page to image using pdf.js
        setExtractMsg('📄 Converting PDF to image…');
        const pdfjsLib = await import('pdfjs-dist');
        pdfjsLib.GlobalWorkerOptions.workerSrc = `https://cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjsLib.version}/pdf.worker.min.js`;

        const arrayBuffer = await file.arrayBuffer();
        const pdf = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
        const page = await pdf.getPage(1);

        const viewport = page.getViewport({ scale: 2.0 }); // 2x scale for clarity
        const canvas = document.createElement('canvas');
        canvas.width = viewport.width;
        canvas.height = viewport.height;
        const ctx = canvas.getContext('2d')!;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await page.render({ canvas, canvasContext: ctx as any, viewport }).promise;

        const dataUrl = canvas.toDataURL('image/jpeg', 0.9);
        base64 = dataUrl.split(',')[1];
        mimeType = 'image/jpeg';
        // Show the rendered page as preview
        setUploadPreview(dataUrl);
        setExtractMsg('');
      } else {
        // Image file — read directly
        const reader = new FileReader();
        base64 = await new Promise<string>((resolve, reject) => {
          reader.onload = (ev) => resolve((ev.target?.result as string).split(',')[1]);
          reader.onerror = reject;
          reader.readAsDataURL(file);
        });
        mimeType = file.type || 'image/jpeg';
      }

      const res = await fetch('/api/extract-soil', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ image: base64, mimeType }),
      });

      if (!res.ok) throw new Error('Extraction failed');
      const data = await res.json();

      setForm((f) => ({
        ...f,
        nitrogen:   data.nitrogen   > 0 ? data.nitrogen   : f.nitrogen,
        phosphorus: data.phosphorus > 0 ? data.phosphorus : f.phosphorus,
        potassium:  data.potassium  > 0 ? data.potassium  : f.potassium,
        ph:         data.ph         > 0 ? data.ph         : f.ph,
        moisture:   data.moisture   > 0 ? data.moisture   : f.moisture,
      }));

      const confidenceEmoji = data.confidence === 'high' ? '✅' : data.confidence === 'medium' ? '⚠️' : '❓';
      setExtractMsg(`${confidenceEmoji} Auto-filled from report (${data.confidence} confidence). ${data.rawText ? data.rawText.slice(0, 80) : ''}`);
    } catch (err) {
      console.error('Extract error:', err);
      setExtractMsg('⚠️ Could not auto-extract — please fill values manually.');
    } finally {
      setExtracting(false);
    }
  };

  const tabs = [{ key: 'form', label: 'Input', icon: '📋' }, { key: 'crops', label: 'Crops', icon: '🌾' }, { key: 'correction', label: 'Fix Soil', icon: '🔧' }];

  return (
    <div className="app-light min-h-screen relative overflow-hidden">
      <div className="orb w-72 h-72 -top-16 -right-16" style={{ background: '#22c55e' }} />
      <div className="orb w-48 h-48 bottom-24 -left-12" style={{ background: '#f59e0b', animationDelay: '2s' }} />

      <div className="relative max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 pt-8 page-enter">
        <h1 className="text-2xl font-bold gradient-text mb-1">Soil Analysis</h1>
        <p className="text-sm mb-5" style={{ color: 'var(--text-secondary)' }}>AI-powered crop recommendations from your soil data</p>

        {/* Tab Bar */}
        <div className="flex gap-1 mb-5 p-1 rounded-2xl" style={{ background: 'rgba(255,255,255,0.82)', border: '1px solid rgba(21,128,61,0.12)', boxShadow: '0 10px 28px rgba(15,23,42,0.05)' }}>
          {tabs.map((t) => (
            <button key={t.key} onClick={() => t.key !== 'form' && result ? setTab(t.key as Tab) : t.key === 'form' ? setTab('form') : null}
              className="flex-1 py-2.5 text-sm font-semibold rounded-xl transition-all flex items-center justify-center gap-1.5"
              style={{
                background: tab === t.key ? '#22c55e' : 'transparent',
                color: tab === t.key ? '#061a0d' : t.key !== 'form' && !result ? 'rgba(22,50,34,0.45)' : 'rgba(22,50,34,0.72)',
                cursor: t.key !== 'form' && !result ? 'not-allowed' : 'pointer',
              }}>
              <span>{t.icon}</span> {t.label}
            </button>
          ))}
        </div>

        {/* FORM TAB */}
        {tab === 'form' && (
          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Upload Soil Report Card */}
            <div className="glass-card rounded-2xl p-5">
              <div className="flex items-center gap-2 mb-3">
                <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: 'rgba(99,102,241,0.15)' }}>
                  <span className="text-base">📄</span>
                </div>
                <div>
                  <h3 className="font-bold" style={{ color: '#a78bfa' }}>Upload Soil Test Report</h3>
                  <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Photo or PDF — AI will auto-fill values</p>
                </div>
              </div>

              <label style={{
                display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
                gap: 8, padding: '20px 16px', borderRadius: 12, cursor: 'pointer',
                border: uploadFile ? '2px solid #7c3aed' : '2px dashed rgba(124,58,237,0.24)',
                background: uploadFile ? 'rgba(99,102,241,0.1)' : 'rgba(255,255,255,0.92)',
                transition: 'all 0.2s',
              }}>
                <input
                  type="file"
                  accept="image/*,application/pdf"
                  style={{ display: 'none' }}
                  onChange={handleFileChange}
                />
                {uploadPreview ? (
                  <img src={uploadPreview} alt="Soil report" style={{ maxHeight: 140, borderRadius: 8, objectFit: 'contain' }} />
                ) : (
                  <span style={{ fontSize: 32 }}>{uploadFile ? '📑' : '📸'}</span>
                )}
                <span style={{ fontSize: 13, color: uploadFile ? '#6d28d9' : 'rgba(22,50,34,0.62)', fontWeight: 600, textAlign: 'center' }}>
                  {uploadFile ? uploadFile.name : 'Tap to upload photo or PDF of soil report'}
                </span>
                {!uploadFile && (
                  <span style={{ fontSize: 11, color: 'rgba(22,50,34,0.5)' }}>JPG, PNG, PDF supported</span>
                )}
              </label>

              {/* Extraction status */}
              {extracting && (
                <div style={{ marginTop: 10, display: 'flex', alignItems: 'center', gap: 8, color: '#6d28d9', fontSize: 13, fontWeight: 600 }}>
                  <span style={{ display: 'inline-block', animation: 'spin 1s linear infinite' }}>⏳</span>
                  Analyzing report with Gemini AI…
                </div>
              )}
              {extractMsg && !extracting && (
                <div style={{
                  marginTop: 10, padding: '8px 12px', borderRadius: 8, fontSize: 12,
                  background: extractMsg.startsWith('✅') ? 'rgba(34,197,94,0.1)' : 'rgba(245,158,11,0.1)',
                  color: extractMsg.startsWith('✅') ? '#166534' : '#b45309',
                  border: `1px solid ${extractMsg.startsWith('✅') ? 'rgba(34,197,94,0.3)' : 'rgba(245,158,11,0.3)'}`,
                }}>
                  {extractMsg}
                </div>
              )}

              {uploadFile && (
                <button type="button" onClick={() => { setUploadFile(null); setUploadPreview(''); setExtractMsg(''); }}
                  style={{ marginTop: 8, fontSize: 12, color: 'var(--text-muted)', background: 'none', border: 'none', cursor: 'pointer', padding: 0 }}>
                  ✕ Remove file
                </button>
              )}
            </div>

            <div className="glass-card rounded-2xl p-5">
              <div className="flex items-center gap-2 mb-4">
                <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: 'rgba(34,197,94,0.15)' }}>
                  <span className="text-base">🧪</span>
                </div>
                <h3 className="font-bold" style={{ color: 'var(--accent-green)' }}>NPK Values <span className="font-normal text-xs" style={{ color: 'var(--text-muted)' }}>(kg/ha)</span></h3>
              </div>
              <div className="grid grid-cols-3 gap-3">
                {[
                  { key: 'nitrogen', label: 'Nitrogen (N)', color: '#22c55e', placeholder: '40' },
                  { key: 'phosphorus', label: 'Phosphorus (P)', color: '#f59e0b', placeholder: '20' },
                  { key: 'potassium', label: 'Potassium (K)', color: '#60a5fa', placeholder: '30' },
                ].map(({ key, label, color, placeholder }) => (
                  <div key={key}>
                    <label className="block text-xs font-semibold mb-1.5" style={{ color }}>{label}</label>
                    <input type="number" required min={0} placeholder={placeholder}
                      value={form[key as keyof SoilData] || ''}
                      onChange={(e) => setForm({ ...form, [key]: parseFloat(e.target.value) || 0 })}
                      className="input-field text-center font-bold" style={{ borderColor: color + '40' }} />
                  </div>
                ))}
              </div>
            </div>

            <div className="glass-card rounded-2xl p-5">
              <div className="flex items-center gap-2 mb-4">
                <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: 'rgba(245,158,11,0.15)' }}>
                  <span className="text-base">📊</span>
                </div>
                <h3 className="font-bold" style={{ color: 'var(--accent-amber)' }}>Soil Conditions</h3>
              </div>
              <div className="grid grid-cols-2 gap-3 mb-3">
                <div>
                  <label className="block text-xs font-semibold mb-1.5" style={{ color: 'var(--text-muted)' }}>pH Level <span style={{ color: 'rgba(22,50,34,0.42)' }}>(0–14)</span></label>
                  <input type="number" step="0.1" min={0} max={14} required value={form.ph}
                    onChange={(e) => setForm({ ...form, ph: parseFloat(e.target.value) || 7 })}
                    className="input-field" />
                </div>
                <div>
                  <label className="block text-xs font-semibold mb-1.5" style={{ color: 'var(--text-muted)' }}>Moisture <span style={{ color: 'rgba(22,50,34,0.42)' }}>(%)</span></label>
                  <input type="number" min={0} max={100} required value={form.moisture}
                    onChange={(e) => setForm({ ...form, moisture: parseFloat(e.target.value) || 0 })}
                    className="input-field" />
                </div>
              </div>
              <div>
                <label className="block text-xs font-semibold mb-1.5" style={{ color: 'var(--text-muted)' }}>📍 Location</label>
                <input type="text" required placeholder="Village, District, State" value={form.location}
                  onChange={(e) => setForm({ ...form, location: e.target.value })}
                  className="input-field" />
              </div>
            </div>

            <div className="glass-card rounded-2xl p-5">
              <div className="flex items-center gap-2 mb-1">
                <span className="text-base">🎯</span>
                <h3 className="font-bold" style={{ color: 'var(--text-primary)' }}>Preferred Crop <span className="font-normal text-xs" style={{ color: 'var(--text-muted)' }}>(Optional)</span></h3>
              </div>
              <p className="text-xs mb-3" style={{ color: 'var(--text-muted)' }}>Already know what you want to grow? Get a tailored soil correction plan.</p>
              <input type="text" placeholder="e.g. Wheat, Rice, Cotton, Sugarcane..." value={form.preferred_crop}
                onChange={(e) => setForm({ ...form, preferred_crop: e.target.value })}
                className="input-field" />
            </div>

            {error && <p className="text-sm text-red-400 bg-red-900/20 px-4 py-3 rounded-xl">{error}</p>}

            <button type="submit" disabled={loading} className="btn-primary w-full justify-center py-4 text-base rounded-2xl">
              {loading ? (
                <><span className="spinner" style={{ width: 18, height: 18, borderWidth: 2 }} /> Analyzing with AI...</>
              ) : (
                <>🤖 Get AI Recommendations</>
              )}
            </button>
          </form>
        )}

        {/* CROPS TAB */}
        {tab === 'crops' && result && (
          <div className="space-y-4">
            <div className="glass-card rounded-2xl px-4 py-3 flex items-start gap-2">
              <span className="text-lg mt-0.5">💡</span>
              <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>{result.summary}</p>
            </div>
            {result.topCrops.map((crop, i) => (
              <div key={i} className="glass-card rounded-2xl p-5" style={{ border: i === 0 ? '1px solid rgba(34,197,94,0.3)' : undefined }}>
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-9 h-9 rounded-xl flex items-center justify-center font-black text-sm flex-shrink-0"
                    style={{ background: i === 0 ? '#22c55e' : 'rgba(34,197,94,0.12)', color: i === 0 ? '#061a0d' : '#4ade80' }}>
                    #{i + 1}
                  </div>
                  <div>
                    <h3 className="font-bold" style={{ color: 'var(--text-primary)' }}>{crop.name}</h3>
                    {i === 0 && <span className="badge badge-green text-xs">Best Match</span>}
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-3 mb-3">
                  <div className="rounded-xl p-3" style={{ background: 'rgba(34,197,94,0.08)' }}>
                    <p className="text-xs mb-1" style={{ color: 'var(--text-muted)' }}>📈 Expected Yield</p>
                    <p className="font-bold text-sm" style={{ color: '#4ade80' }}>{crop.expectedYield}</p>
                  </div>
                  <div className="rounded-xl p-3" style={{ background: 'rgba(245,158,11,0.08)' }}>
                    <p className="text-xs mb-1" style={{ color: 'var(--text-muted)' }}>💰 Input Cost</p>
                    <p className="font-bold text-sm" style={{ color: '#fcd34d' }}>{crop.inputCostEstimate}</p>
                  </div>
                </div>
                  <div className="rounded-xl p-3 mb-3" style={{ background: 'rgba(255,255,255,0.72)', border: '1px solid rgba(21,128,61,0.08)' }}>
                  <p className="text-xs font-semibold mb-1.5" style={{ color: 'var(--text-muted)' }}>💸 Cost Breakdown</p>
                  <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>{crop.costBreakdown}</p>
                </div>
                <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>📌 {crop.careTips}</p>
              </div>
            ))}
            {/* Share & Export */}
            <div className="flex gap-3">
              <button onClick={() => shareOnWhatsApp(form, result)} className="flex-1 flex items-center justify-center gap-2 py-3 rounded-2xl text-sm font-semibold transition-all"
                style={{ background: 'rgba(37,211,102,0.1)', color: '#15803d', border: '1px solid rgba(21,128,61,0.18)' }}>
                📲 Share on WhatsApp
              </button>
              <button onClick={() => downloadPDF(form, result)} className="flex-1 flex items-center justify-center gap-2 py-3 rounded-2xl text-sm font-semibold transition-all"
                style={{ background: 'rgba(59,130,246,0.08)', color: '#1d4ed8', border: '1px solid rgba(59,130,246,0.16)' }}>
                📄 Download PDF
              </button>
            </div>
            <button onClick={() => { setTab('form'); setResult(null); }} className="btn-secondary w-full">← Analyze Again</button>
            <SoilHistoryChart />
          </div>
        )}

        {/* CORRECTION TAB */}
        {tab === 'correction' && result && (
          <div className="space-y-3">
            {result.soilCorrectionPlan.targetCropNote && (
              <div className="glass-card-amber rounded-2xl p-4 flex gap-3">
                <span className="text-2xl">🎯</span>
                <div>
                  <p className="text-xs font-semibold mb-1" style={{ color: '#fcd34d' }}>Tailored for Your Crop</p>
                  <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>{result.soilCorrectionPlan.targetCropNote}</p>
                </div>
              </div>
            )}
            {[
              { icon: '🟢', label: 'Nitrogen Fix', value: result.soilCorrectionPlan.nitrogenFix, color: '#22c55e' },
              { icon: '🔵', label: 'Phosphorus Fix', value: result.soilCorrectionPlan.phosphorusFix, color: '#60a5fa' },
              { icon: '🟡', label: 'Potassium Fix', value: result.soilCorrectionPlan.potassiumFix, color: '#fcd34d' },
              { icon: '⚗️', label: 'pH Correction', value: result.soilCorrectionPlan.phCorrection, color: '#c084fc' },
              { icon: '🌿', label: 'Organic Alternatives', value: result.soilCorrectionPlan.organicAlternatives, color: '#4ade80' },
            ].map((item) => (
              <div key={item.label} className="glass-card rounded-2xl p-4 flex gap-3">
                <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 text-lg" style={{ background: item.color + '15' }}>
                  {item.icon}
                </div>
                <div>
                  <p className="text-xs font-bold mb-1" style={{ color: item.color }}>{item.label}</p>
                  <p className="text-sm" style={{ color: 'var(--text-primary)' }}>{item.value}</p>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
